# Generated by Django 4.2.13 on 2026-05-28 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('vencido', 'Vencido')], default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='herramientas.herramienta')),
            ],
            options={
                'verbose_name_plural': 'préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
