# Generated by Django 4.2.13 on 2026-05-28 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herramientas', '0001_initial'),
        ('prestamos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='herramienta',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='solicitante',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='descripcion_uso',
            field=models.TextField(blank=True, default='', verbose_name='¿Para qué se va a usar?'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='herramientas',
            field=models.ManyToManyField(related_name='prestamos', to='herramientas.herramienta'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='lugar_uso',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lugar de uso'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='solicitantes',
            field=models.ManyToManyField(related_name='prestamos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
